version: "3.9"

services:
  db:
    image: postgres:13
    volumes:
      - db-data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=scancodeio
      - POSTGRES_USER=scancodeio
      - POSTGRES_PASSWORD=scancodeio

  redis:
    image: redis

  celery:
    build: .
    environment:
      - SCANCODEIO_DB_HOST=db
      - SCANCODEIO_WORKSPACE_LOCATION=/var/scancodeio/workspace
      - CELERY_TASK_ALWAYS_EAGER=False
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    command: celery --app scancodeio worker --loglevel=INFO
    volumes:
      - .:/opt/scancodeio
      - workspace:/var/scancodeio/workspace
    depends_on:
      - redis
      - db

  web:
    build: .
    environment:
      - SCANCODEIO_DB_HOST=db
      - SCANCODEIO_WORKSPACE_LOCATION=/var/scancodeio/workspace
      - CELERY_TASK_ALWAYS_EAGER=False
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    command: sh -c "
      python manage.py migrate &&
      python manage.py collectstatic --no-input &&
      python manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
    volumes:
      - .:/opt/scancodeio
      - workspace:/var/scancodeio/workspace
      - static:/var/scancodeio/static
    depends_on:
      - db

volumes:
  db-data:
  static:
  workspace:
