version: "3.9"

services:
  db:
    image: postgres:13
    volumes:
      - db_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=scancodeio
      - POSTGRES_USER=scancodeio
      - POSTGRES_PASSWORD=scancodeio

  redis:
    image: redis

  celery:
    build: .
    environment:
      - SCANCODEIO_DB_HOST=db
      - SCANCODEIO_WORKSPACE_LOCATION=/var/scancodeio/workspace/
      - CELERY_TASK_ALWAYS_EAGER=False
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    command: celery --app scancodeio worker --loglevel=INFO
    volumes:
      - .:/opt/scancodeio/
      - workspace:/var/scancodeio/workspace/
    depends_on:
      - redis
      - db

  web:
    build: .
    environment:
      - SCANCODEIO_DB_HOST=db
      - SCANCODEIO_WORKSPACE_LOCATION=/var/scancodeio/workspace/
      - CELERY_TASK_ALWAYS_EAGER=False
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    command: sh -c "
        ./manage.py migrate &&
        ./manage.py collectstatic --no-input &&
        gunicorn scancodeio.wsgi:application --bind :8000 --timeout 600 --workers 3"
    expose:
      - 8000
    volumes:
      - .:/opt/scancodeio/
      - workspace:/var/scancodeio/workspace/
      - static:/var/scancodeio/static/
    depends_on:
      - db

  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./etc/nginx/conf.d/:/etc/nginx/conf.d/
      - static:/var/scancodeio/static/
    depends_on:
      - web

volumes:
  db_data:
  static:
  workspace:
